[programs.devnet]
helloworld = "FffcgRs2RDsZTVDuiuErHVoTJCHUPcnT46eH3VpycmFi"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/imentus/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
